version: '3'

services:
  app:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/home/node/app
  
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: server-sent-events-db
    ports:
      - 3306:3306